### ISSUE TITLE
connet wallet button

### ISSUE THREAD

**Issue by Daniel-Kenan** [CodeGrepper/grepper_contributor_coin_contract#2]
# connect wallet throwing errors
showing
> Current GREPCC Balance: Unkown (wallet not connected) 

and when I try to click connect wallet it throws an error.
***please note phantom is already installed***

**Comment by Gokuss7** [comment]
Same issue here, the button connect is available but does nothing and in the Phantom app it says we are connected to Grepper?? 
![image](https://user-images.githubusercontent.com/64170383/174664827-a68e7bd1-ecdb-4f37-a278-9e616e742e62.png)

**Comment by TaylorHawkes** [comment]
Generally this issue resolves after about 1 minute after you connect your wallet for the first time. Let me know if anyone is continually seeing/having this issue.
